dominique-mueller/angular-package-builder

- .gitignore
- .travis.yml
- README.md
- bin/angular-package-builder.js
- index.ts
- package.json
- tsconfig.json
- Add gitignore file
- Add Travis CI configuration file
- Add package.json
- Add src entry files
- Add tsconfig file
> feat(*): Add initial project setup

- .gitignore
- example-library/lib/src/components/notifier-notification.component.ts
- index.ts
- package-lock.json
- package.json
- src/config/rollup.config.interface.ts
- src/config/rollup.config.ts
- src/config/typescript.config.interface.ts
- src/config/typescript.config.ts
- src/tasks/bundle-javascript.ts
- src/tasks/compile-typescript.ts
- src/tasks/inline-resources.ts
- src/utilities/clean-folder.ts
- src/utilities/normalize-line-endings.ts
- src/utilities/read-file.ts
- src/utilities/write-file.ts
- Add JavaScript bundle generator for FESM2015, FESM5, UMD
- Add custom rollup interfaces
- Refactor parameter names
- Update inner typescript configuration
- Refactor dist folder structure
> feat(bundle): Add JavaScript bundle generator

- index.ts
- package-lock.json
- package.json
- src/config/rollup.config.ts
- src/config/typescript.config.ts
- src/interfaces/angular-package-builder-config.interface.ts
- src/interfaces/package-json.interface.ts
- src/tasks/bundle-javascript.ts
- src/tasks/compile-typescript.ts
- src/tasks/compose-package.ts
- src/tasks/create-config.ts
- src/tasks/inline-resources.ts
- src/utilities/get-files.ts
- src/utilities/get-safe-dependency-name.ts
- src/utilities/get-safe-package-name.ts
- src/utilities/read-file.ts
- Add create configuration task
- Add package.json reader (name, dependencie)
- Add gitignore reader
- Add two utilities for generating safe package names
- Extract Angular Package Builder interface
- Add PackageJson interface
- Fix readFile utility return interface
> feat(config): Add create config task, including package.json & gitignore reader

- example-library/lib/src/services/notifier-timer.service.ts
- src/angular-package-builder.schema.json
- src/config/typescript.config.interface.ts
- src/config/typescript.config.ts
- src/memory-file-system.ts
- Add configuration file JSON schema
- Fix tsconfig typeRoots (now working as expected)
- Fix TypeScript typeRoots reader (now accessing the real filesystem)
- Extend internal tsconfig (plus possible options for debug mode, commented out for now)
- Fix typings in library example
> feat(config): Add configuration file JSON schema

- package-lock.json
- package.json
- src/tasks/inline-resources.ts
- Add SASS compiler
- Add CSS minifier
> feat(inline-resources): Add SASS compiler, add CSS minifier

- index.ts
- package-lock.json
- package.json
- src/angular-resource-analyzer.ts
- src/angular-resource-analyzer/angular-resource-analyzer.ts
- src/angular-resource-analyzer/angular-resource-url.interface.ts
- src/angular-resource-analyzer/angular-resource.interface.ts
- src/memory-file-system/memory-file-system.ts
- src/resources/compile-sass.ts
- src/resources/minify-css.ts
- src/resources/minify-html.ts
- src/tasks/bundle-javascript.ts
- src/tasks/compile-typescript.ts
- src/tasks/compose-package.ts
- src/tasks/inline-resources.ts
- src/utilities/dynamic-import.ts
- Move functionality from inline resource step into angular resource analyer
- Add interfaces for the angular resource analyzer
- Extract resource tasks (compile & minify) into separate files
- Add typings for resource task
- Refactor file / folder structure
> refactor(inline-resources): Refactor inline resources step

- .angular-package.json
- index.ts
- package-lock.json
- package.json
- src/angular-package.schema.json
- src/config/rollup.config.ts
- src/config/typescript.config.ts
- src/interfaces/angular-package-builder-config.interface.ts
- src/interfaces/angular-package-builder-internal-config.interface.ts
- src/memory-file-system/memory-file-system.ts
- src/resources/compile-sass.ts
- src/resources/minify-css.ts
- src/static/angular.dependencies.ts
- src/static/rxjs.dependencies.ts
- src/tasks/bundle-javascript.ts
- src/tasks/compile-typescript.ts
- src/tasks/compose-package.ts
- src/tasks/create-config.ts
- src/tasks/inline-resources.ts
- src/utilities/copy.ts
- src/utilities/delete-folder.ts
- src/utilities/dynamic-import.ts
- src/utilities/get-dependency-map.ts
- src/utilities/get-files.ts
- src/utilities/get-safe-dependency-name.ts
- src/utilities/get-safe-package-name.ts
- src/utilities/write-file.ts
- test-library/src/services/store.service.ts
- tsconfig.json
- Upgrade to Angular 5 (plus update other dependencies as well)
- Switch from tsc-wrapped to compiler-cli
- Update external and internal angular package builder configuration (incl. JSON schema)
- Overall refactoring (async-await, file splitting, ...)
- Update configurations and configuration merging strategy
- Update tsconfig
> refactor(*): Upgrade to Angular 5, refactoring

- README.md
- Update folder structure details
- Add link to list of example repos
> docs(README): Update how to use guide

- package-lock.json
- package.json
- src/config/rollup.config.ts
- src/config/typescript.config.ts
- src/internal-config.interface.ts
- src/tasks/bundle.ts
- src/tasks/configure.ts
- src/utilities/get-safe-dependency-name.ts
- Fix output file names for sub-modules
- Remove no longer needed dependency
- Fix TypeScript interfaces
Closes #77.
> fix(config): Fix output file names for sub-modules

- src/config/rollup.config.ts
- Supress rollup optimization warnings
Closes #76.
> fix(logging): Supress rollup optimization warnings

- README.md
- Add section on synthetic imports
- Remove Synk badge (no relevance)
Closes #75.
> docs(pitfalls): Add section on synthetic imports

- src/config/rollup.config.ts
- Supress rollup warnings
Closes #76.
> fix(logging): Supress rollup warnings - for real now!

- index.ts
- src/angular-package-builder.ts
- src/angular-package-config.interface.ts
- src/angular-package-reader.ts
- src/angular-package.ts
- src/bundler/angular-package.bundler.ts
- src/bundler/rollup-configuration-builder.ts
- src/compiler/angular-package.compiler.ts
- src/composer/angular-package.composer.ts
- src/transformer/angular-package.transformer.ts
- src/transformer/external-resources/angular-external-resources.analyzer.ts
- src/utilities/create-typescript-project.ts
- src/utilities/delete-folder.ts
- src/utilities/ensure-dependency-version.ts
- src/utilities/get-file-type.ts
- src/utilities/read-file.ts
- test/spec/config.ts
- test/spec/esm2015.spec.ts
- test/spec/esm5.spec.ts
- test/spec/fesm2015.spec.ts
- test/spec/fesm5.spec.ts
- test/spec/metadata.spec.ts
- test/spec/typings.spec.ts
- test/spec/umd.spec.ts
- Add Angular Package Composer
- Refactor Angular Package Builder
- Add temporary output cleanup before and after package process
> feat(package): Add creation of package.json file incl. entry points

- .pullapprove.yml
- Add pullapprove configuration
> chore(workflow): Add pullapprove configuration

- .travis.yml
- package-lock.json
- package.json
- src/bundler/angular-package.bundler.ts
- src/compiler/angular-package.compiler.ts
- src/logger/logger-symbols.ts
- src/transformer/angular-package.transformer.ts
- src/transformer/external-styles/angular-external-styles.transformer.ts
- src/transformer/external-templates/angular-external-templates.transformer.ts
- src/transformer/languages/css.transformer.ts
- src/transformer/languages/html.transformer.ts
- src/transformer/languages/sass.transformer.ts
- test/errors/errors.spec.ts
- test/errors/packages/library-error-rollup/.angular-package.json
- test/errors/packages/library-error-rollup/.gitignore
- test/errors/packages/library-error-rollup/build.ts
- test/errors/packages/library-error-rollup/index.ts
- test/errors/packages/library-error-rollup/package.json
- test/errors/packages/library-error-rollup/src/input/input.component.html
- test/errors/packages/library-error-rollup/src/input/input.component.scss
- test/errors/packages/library-error-rollup/src/input/input.component.ts
- test/errors/packages/library-error-rollup/src/library.module.ts
- Handle bundling errors
- Add tests
- Align error messages
> feat(errors): Handle bundling errors, add tests

- .travis.yml
- codecov.yml
- package-lock.json
- package.json
- Add codecov configuration
- Add codecov to npm scripts & travis ci
> chore(codecov): Add codecov

- .travis.yml
- test/single-library/build.js
- test/single-library/packages/build.ts
- test/single-library/packages/library/.angular-package.json
- test/single-library/packages/library/.gitignore
- test/single-library/packages/library/index.ts
- test/single-library/packages/library/package.json
- test/single-library/packages/library/src/input/input.component.html
- test/single-library/packages/library/src/input/input.component.scss
- test/single-library/packages/library/src/input/input.component.ts
- test/single-library/packages/library/src/library.module.ts
- test/single-library/packages/tsconfig.json
- test/single-library/single-library.spec.ts
- Add single library tests w/ example
- Extend travis ci configuration
> test(*): Add single library tests w/ example

- package-lock.json
- package.json
- src/transformer/languages/sass.transformer.ts
- Add support for tilde imports
> feat(sass): Add support for tilde-imports

- README.md
- package.json
> docs(README): Improve documentation

- src/compiler/typescript-configuration-builder.ts
- Fix compiler options merge strategy to allow all options to be changed
> fix(compiler): Fix compiler options override

- .travis.yml
- README.md
- package-lock.json
- package.json
- Add Angular 6.1 support
- Extend travis test matrix
> feat(*): Add Angular 6.1 support
